spring.application.name=ecommerce

# Server configuration
server.port=5000
server.servlet.context-path=/api

# Active profile
spring.profiles.active=dev


# Spring Security default user (if used)
spring.security.user.name=admin
spring.security.user.password=admin123

# Logging levels
logging.level.com.rushabh.ecommerce=DEBUG
logging.level.org.springframework.security=DEBUG

# Console log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n



